_target_: promptttspp.vocoders.F0AwareBigVGAN
sampling_rate: 24000
harmonic_num: 8
in_channel: 80
upsample_initial_channel: 512
upsample_rates: [6, 5, 4, 2]
upsample_kernel_sizes: [12, 10, 8, 4]
resblock_kernel_sizes: [3, 7, 11]
resblock_dilations: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
